"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Slider } from "@/components/ui/slider"
import { ArrowLeft, ArrowRight, Brain, Lightbulb, MessageSquare, BookOpen } from "lucide-react"

export default function UnderstandingLLMsTutorial() {
  const [currentModule, setCurrentModule] = useState(1)
  const [progress, setProgress] = useState(14)
  const [temperature, setTemperature] = useState([0.7])
  const [topP, setTopP] = useState([0.9])
  const [maxTokens, setMaxTokens] = useState([50])
  const [generatedText, setGeneratedText] = useState(
    "The quick brown fox jumps over the lazy dog. This is a sample text that would be generated by the LLM based on your parameters.",
  )

  const totalModules = 7

  const handleNext = () => {
    if (currentModule < totalModules) {
      setCurrentModule(currentModule + 1)
      setProgress(((currentModule + 1) / totalModules) * 100)
    }
  }

  const handlePrevious = () => {
    if (currentModule > 1) {
      setCurrentModule(currentModule - 1)
      setProgress(((currentModule - 1) / totalModules) * 100)
    }
  }

  // Simulate text generation based on parameters
  const generateText = () => {
    // In a real application, this would call an API to generate text
    // Here we're just simulating different outputs based on parameters

    let newText = ""

    if (temperature[0] < 0.3) {
      newText = "The cat sat on the mat. It was a sunny day. The cat was sleeping peacefully."
    } else if (temperature[0] < 0.7) {
      newText =
        "The orange tabby cat lounged lazily on the colorful mat, basking in the warm sunlight streaming through the window."
    } else {
      newText =
        "The magnificent feline, with fur like burnished copper, sprawled majestically upon the intricately woven tapestry, absorbing the golden rays that cascaded through the crystalline panes like a waterfall of light."
    }

    // Adjust length based on max tokens
    const words = newText.split(" ")
    const adjustedLength = Math.max(3, Math.floor(maxTokens[0] / 5)) // Rough approximation
    newText = words.slice(0, adjustedLength).join(" ")

    setGeneratedText(newText)
  }

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8">
        <div>
          <div className="flex items-center mb-2">
            <Link href="/tutorials" className="text-gray-500 hover:text-gray-700 mr-2">
              <ArrowLeft className="h-4 w-4 inline" /> Back to Tutorials
            </Link>
            <Badge variant="outline">AI Concepts</Badge>
            <Badge variant="outline" className="ml-2">
              Intermediate
            </Badge>
          </div>
          <h1 className="text-3xl font-bold tracking-tighter">Understanding Large Language Models</h1>
          <p className="text-gray-500 mt-2">Interactive exploration of how LLMs work and generate text.</p>
        </div>
        <div className="mt-4 md:mt-0 flex items-center">
          <div className="text-sm text-gray-500 mr-4">Progress: {Math.round(progress)}%</div>
          <Progress value={progress} className="w-[200px] h-2" />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
        {/* Sidebar Navigation */}
        <div className="md:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Tutorial Modules</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <nav className="flex flex-col">
                {[
                  "Introduction to LLMs",
                  "Transformer Architecture",
                  "Tokenization",
                  "Training Process",
                  "Inference & Generation",
                  "Parameters & Fine-tuning",
                  "Limitations & Future",
                ].map((module, index) => (
                  <button
                    key={index}
                    onClick={() => {
                      setCurrentModule(index + 1)
                      setProgress(((index + 1) / totalModules) * 100)
                    }}
                    className={`flex items-center p-3 text-left border-b border-gray-100 hover:bg-gray-50 transition-colors ${
                      currentModule === index + 1 ? "bg-gray-50 font-medium" : ""
                    }`}
                  >
                    <div
                      className={`w-6 h-6 rounded-full flex items-center justify-center mr-3 ${
                        currentModule > index + 1
                          ? "bg-green-100 text-green-600"
                          : currentModule === index + 1
                            ? "bg-blue-100 text-blue-600"
                            : "bg-gray-100 text-gray-400"
                      }`}
                    >
                      {index + 1}
                    </div>
                    <span className="text-sm">{module}</span>
                  </button>
                ))}
              </nav>
            </CardContent>
          </Card>
        </div>

        {/* Main Content */}
        <div className="md:col-span-3">
          <Card className="mb-6">
            <CardHeader>
              <CardTitle>
                {currentModule === 1 && "Introduction to Large Language Models"}
                {currentModule === 2 && "Transformer Architecture"}
                {currentModule === 3 && "Tokenization: How LLMs Process Text"}
                {currentModule === 4 && "Training Process"}
                {currentModule === 5 && "Inference & Text Generation"}
                {currentModule === 6 && "Parameters & Fine-tuning"}
                {currentModule === 7 && "Limitations & Future Directions"}
              </CardTitle>
              <CardDescription>
                {currentModule === 1 && "Understanding what LLMs are and how they're used"}
                {currentModule === 2 && "Exploring the architecture behind modern language models"}
                {currentModule === 3 && "How text is converted into tokens for processing"}
                {currentModule === 4 && "How LLMs learn from vast amounts of text data"}
                {currentModule === 5 && "How models generate text responses"}
                {currentModule === 6 && "Adjusting model behavior with parameters"}
                {currentModule === 7 && "Current limitations and future developments"}
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Module 5: Inference & Text Generation */}
              {currentModule === 5 && (
                <div className="space-y-6">
                  <div>
                    <h3 className="text-lg font-medium mb-2">How LLMs Generate Text</h3>
                    <p className="text-gray-600 mb-4">
                      During inference (text generation), an LLM predicts the next token based on the tokens it has seen
                      so far. This process happens one token at a time, with each new token being influenced by all
                      previous tokens.
                    </p>
                  </div>

                  <div className="bg-blue-50 p-4 rounded-lg mb-6">
                    <h3 className="text-lg font-medium flex items-center mb-2">
                      <Lightbulb className="h-5 w-5 text-blue-500 mr-2" />
                      Key Concepts in Text Generation
                    </h3>
                    <ul className="list-disc pl-5 space-y-2 text-gray-600">
                      <li>
                        <span className="font-medium">Temperature:</span> Controls randomness in generation
                      </li>
                      <li>
                        <span className="font-medium">Top-p (nucleus sampling):</span> Controls diversity of outputs
                      </li>
                      <li>
                        <span className="font-medium">Max tokens:</span> Limits the length of generated text
                      </li>
                      <li>
                        <span className="font-medium">Repetition penalty:</span> Discourages repeating the same phrases
                      </li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-lg font-medium mb-4">Interactive Text Generation Simulator</h3>
                    <p className="text-gray-600 mb-6">
                      Adjust the parameters below to see how they affect text generation. In a real LLM, these
                      parameters would influence the model's outputs in similar ways.
                    </p>

                    <Tabs defaultValue="parameters" className="w-full">
                      <TabsList className="grid w-full grid-cols-2">
                        <TabsTrigger value="parameters">Parameters</TabsTrigger>
                        <TabsTrigger value="explanation">Explanation</TabsTrigger>
                      </TabsList>
                      <TabsContent value="parameters" className="space-y-6 pt-4">
                        <div>
                          <div className="flex justify-between mb-2">
                            <label className="text-sm font-medium">Temperature: {temperature[0].toFixed(1)}</label>
                            <span className="text-xs text-gray-500">Controls randomness</span>
                          </div>
                          <Slider value={temperature} min={0.1} max={1.5} step={0.1} onValueChange={setTemperature} />
                          <div className="flex justify-between text-xs text-gray-500 mt-1">
                            <span>More deterministic</span>
                            <span>More random</span>
                          </div>
                        </div>

                        <div>
                          <div className="flex justify-between mb-2">
                            <label className="text-sm font-medium">Top-p: {topP[0].toFixed(1)}</label>
                            <span className="text-xs text-gray-500">Controls diversity</span>
                          </div>
                          <Slider value={topP} min={0.1} max={1.0} step={0.1} onValueChange={setTopP} />
                          <div className="flex justify-between text-xs text-gray-500 mt-1">
                            <span>More focused</span>
                            <span>More diverse</span>
                          </div>
                        </div>

                        <div>
                          <div className="flex justify-between mb-2">
                            <label className="text-sm font-medium">Max Tokens: {maxTokens[0]}</label>
                            <span className="text-xs text-gray-500">Controls length</span>
                          </div>
                          <Slider value={maxTokens} min={10} max={100} step={5} onValueChange={setMaxTokens} />
                          <div className="flex justify-between text-xs text-gray-500 mt-1">
                            <span>Shorter</span>
                            <span>Longer</span>
                          </div>
                        </div>

                        <Button onClick={generateText}>Generate Text</Button>

                        <div className="p-4 bg-gray-50 rounded-lg border">
                          <h4 className="font-medium mb-2">Generated Text:</h4>
                          <p className="text-gray-600">{generatedText}</p>
                        </div>
                      </TabsContent>

                      <TabsContent value="explanation" className="space-y-4 pt-4">
                        <div>
                          <h4 className="font-medium mb-2">Temperature</h4>
                          <p className="text-gray-600 mb-2">
                            Temperature controls the randomness of the model's outputs:
                          </p>
                          <ul className="list-disc pl-5 space-y-1 text-gray-600">
                            <li>
                              <span className="font-medium">Low temperature (0.1-0.4):</span> More deterministic,
                              predictable responses
                            </li>
                            <li>
                              <span className="font-medium">Medium temperature (0.5-0.8):</span> Balanced creativity and
                              coherence
                            </li>
                            <li>
                              <span className="font-medium">High temperature (0.9+):</span> More random, creative, and
                              sometimes incoherent responses
                            </li>
                          </ul>
                        </div>

                        <div>
                          <h4 className="font-medium mb-2">Top-p (Nucleus Sampling)</h4>
                          <p className="text-gray-600 mb-2">
                            Top-p sampling considers only the tokens whose cumulative probability exceeds the specified
                            value:
                          </p>
                          <ul className="list-disc pl-5 space-y-1 text-gray-600">
                            <li>
                              <span className="font-medium">Low top-p (0.1-0.4):</span> Considers only the most likely
                              tokens
                            </li>
                            <li>
                              <span className="font-medium">Medium top-p (0.5-0.8):</span> Balanced between likely and
                              diverse tokens
                            </li>
                            <li>
                              <span className="font-medium">High top-p (0.9+):</span> Considers a wider range of
                              possible tokens
                            </li>
                          </ul>
                        </div>

                        <div>
                          <h4 className="font-medium mb-2">Max Tokens</h4>
                          <p className="text-gray-600">
                            This simply limits the length of the generated text. Each token is roughly equivalent to 4
                            characters or 3/4 of a word in English.
                          </p>
                        </div>
                      </TabsContent>
                    </Tabs>
                  </div>

                  <div className="bg-purple-50 p-4 rounded-lg">
                    <h3 className="text-lg font-medium flex items-center mb-2">
                      <Brain className="h-5 w-5 text-purple-500 mr-2" />
                      How This Relates to Prompt Engineering
                    </h3>
                    <p className="text-gray-600 mb-2">
                      Understanding how LLMs generate text helps you craft more effective prompts:
                    </p>
                    <ul className="list-disc pl-5 space-y-1 text-gray-600">
                      <li>For factual or coding tasks, use lower temperature for more deterministic outputs</li>
                      <li>For creative writing or brainstorming, use higher temperature</li>
                      <li>Provide clear context at the beginning of your prompt to guide the generation process</li>
                      <li>Remember that the model generates one token at a time, building on previous context</li>
                    </ul>
                  </div>
                </div>
              )}

              {/* Other modules would be implemented similarly */}
              {currentModule !== 5 && (
                <div className="flex items-center justify-center p-8">
                  <div className="text-center">
                    <BookOpen className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                    <h3 className="text-lg font-medium mb-2">Module Content</h3>
                    <p className="text-gray-500">
                      This module's content would be implemented similarly to Module 5, with interactive elements and
                      explanations relevant to the topic.
                    </p>
                  </div>
                </div>
              )}
            </CardContent>
            <CardFooter className="flex justify-between">
              <Button variant="outline" onClick={handlePrevious} disabled={currentModule === 1}>
                <ArrowLeft className="mr-2 h-4 w-4" /> Previous
              </Button>
              {currentModule < totalModules ? (
                <Button onClick={handleNext}>
                  Next <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              ) : (
                <Button asChild>
                  <Link href="/tutorials">Complete Tutorial</Link>
                </Button>
              )}
            </CardFooter>
          </Card>

          {/* Discussion Section */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center">
                <MessageSquare className="h-5 w-5 mr-2" />
                Discussion
              </CardTitle>
              <CardDescription>Ask questions or share your thoughts about this tutorial</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="p-4 bg-gray-50 rounded-lg">
                  <div className="flex items-start mb-2">
                    <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center mr-3">
                      <span className="text-green-600 font-medium">TK</span>
                    </div>
                    <div>
                      <p className="font-medium">Tom Kim</p>
                      <p className="text-sm text-gray-500">3 days ago</p>
                    </div>
                  </div>
                  <p className="text-gray-600">
                    The interactive text generation simulator really helped me understand how temperature affects
                    outputs. I've been using ChatGPT for a while but never really understood what those settings meant!
                  </p>
                </div>

                <div className="p-4 bg-gray-50 rounded-lg">
                  <div className="flex items-start mb-2">
                    <div className="w-8 h-8 rounded-full bg-yellow-100 flex items-center justify-center mr-3">
                      <span className="text-yellow-600 font-medium">MJ</span>
                    </div>
                    <div>
                      <p className="font-medium">Maria Johnson</p>
                      <p className="text-sm text-gray-500">1 day ago</p>
                    </div>
                  </div>
                  <p className="text-gray-600">
                    Question: Is there a way to visualize how the attention mechanism works in transformers? I'm having
                    trouble understanding that concept.
                  </p>
                </div>

                <textarea
                  placeholder="Add your comment or question..."
                  className="w-full min-h-[100px] p-3 border rounded-md"
                />
                <Button>Post Comment</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

